name: CI/CD to EC2 (Selective)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    env:
      AWS_REGION: us-east-1
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1  # Only the latest commit is fetched for efficiency

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "/"  # Specify files or directory to copy
        target: "/"  # Specify destination path on EC2 instance
